name: tribes
description: A social platform for connecting family and friends in their private Tribes.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.1+2
  cloud_firestore: ^0.14.3
  firestore_ui: ^1.12.0
  firebase_storage: ^5.0.1
  firebase_messaging: ^7.0.3
  cloud_functions: ^0.7.0+1

  google_sign_in: ^4.5.6
  google_maps_flutter: ^1.0.6
  
  geolocator: ^6.1.7
  geocoder: ^0.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1+1
  flutter_launcher_icons: ^0.8.1 
  font_awesome_flutter: ^8.10.0

  provider: ^4.3.2+2
  get_it: ^5.0.1
  stacked: ^1.7.6
  stacked_services: ^0.5.4+5
  stacked_hooks: ^0.1.3+1
  flutter_hooks: ^0.14.1
  observable_ish: ^2.1.4

  responsive_builder: ^0.3.0
  adaptive_theme: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.3
  flutter_colorpicker: ^0.3.4
  auto_size_text: ^2.1.0
  image_picker: ^0.6.7+14
  multi_image_picker: ^4.7.14
  carousel_slider: ^2.3.1
  cached_network_image: ^2.3.3
  intl: ^0.16.1
  image_cropper: ^1.3.1

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.1 # Depends on flutter_test and flutter_driver
  mockito: ^4.1.3

flutter_icons:
  image_path: "assets/launcher/icon-512.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: TribesRounded
      fonts:
        - asset: assets/fonts/TribesRounded/Tribes-Regular.ttf
        - asset: assets/fonts/TribesRounded/Tribes-Thin.ttf
          style: italic
        - asset: assets/fonts/TribesRounded/Tribes-Bold.ttf
    - family: OleoScriptSwashCaps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Regular.ttf
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
