name: tribes
description: A social platform for connecting family and friends in their private Tribes.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  intl: ^0.17.0 # latest
  provider: ^5.0.0 # latest
  get_it: ^7.2.0 # latest
  responsive_builder: ^0.4.1 # latest
  adaptive_theme: ^2.2.0 # latest
  fluttertoast: ^8.0.8 # latest
  flutter_colorpicker: ^0.5.0 # latest
  auto_size_text: ^2.1.0 # latest

  # Firebase
  firebase_core: ^1.4.0 # latest
  firebase_auth: ^3.0.1 # latest
  cloud_firestore: ^2.4.0 # latest
  cloud_functions: ^3.0.0 # latest
  firebase_storage: ^10.0.1 # latest
  firebase_messaging: ^10.0.4 # latest
  firestore_ui: ^1.20.0 # latest

  # Google Auth
  google_sign_in: ^5.0.5 # latest

  # Google Maps
  google_maps_flutter: ^2.0.6 # latest

  geolocator: ^7.4.0 # latest
  geocoder: ^0.2.1 # latest

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3 # latest
  flutter_launcher_icons: ^0.9.1 # latest
  font_awesome_flutter: ^9.1.0 # latest

  # Stacked
  stacked: ^2.2.3 # latest
  stacked_services: ^0.8.13 # latest
  #stacked_services: ^0.5.4+5
  stacked_hooks: ^0.2.1 # latest
  flutter_hooks: ^0.17.0 # latest

  # Images
  image_picker: ^0.8.2 # latest
  multi_image_picker: ^4.8.1 # latest
  carousel_slider: ^4.0.0 # latest
  cached_network_image: ^3.1.0 # latest
  image_cropper: ^1.4.1 # latest

  # Loading
  flutter_spinkit: ^5.0.0 # latest
  shimmer: ^2.0.0 # latest

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3

dependency_overrides:
  # Fix to dependencies conflict with firebase_ui 1.20.0
  cloud_firestore: ^2.4.0
  cloud_firestore_platform_interface: ^5.3.0

flutter_icons:
  image_path: "assets/launcher/icon-512.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: TribesRounded
      fonts:
        - asset: assets/fonts/TribesRounded/Tribes-Regular.ttf
        - asset: assets/fonts/TribesRounded/Tribes-Thin.ttf
          style: italic
        - asset: assets/fonts/TribesRounded/Tribes-Bold.ttf
    - family: OleoScriptSwashCaps
      fonts:
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Regular.ttf
        - asset: assets/fonts/OleoScriptSwashCaps/OleoScriptSwashCaps-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
